# Generated by Django 3.2.5 on 2021-07-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0004_casesuite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesuite',
            options={'verbose_name': '用例集合表', 'verbose_name_plural': '用例集合表'},
        ),
        migrations.RenameField(
            model_name='casesuite',
            old_name='Suite_desc',
            new_name='suite_desc',
        ),
        migrations.CreateModel(
            name='SuiteCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1, help_text='0：有效，1：无效', verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('case_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfacetestplatform.casesuite', verbose_name='用例集合')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfacetestplatform.testcase', verbose_name='测试用例')),
            ],
        ),
    ]
