# Generated by Django 3.2 on 2021-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0007_testcaseexecuteresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseexecuteresult',
            name='execute_var',
            field=models.CharField(max_length=1024, null=True, verbose_name='关联参数'),
        ),
    ]
