# Generated by Django 3.2 on 2021-07-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0008_testcaseexecuteresult_execute_var'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaseexecuteresult',
            old_name='execute_var',
            new_name='extract_var',
        ),
    ]
