# Generated by Django 3.2 on 2021-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0009_rename_execute_var_testcaseexecuteresult_extract_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseexecuteresult',
            name='exception_info',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
